package com.floapp.agriflo.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Local cache for weather forecast data.
 * Weather is fetched from Open-Meteo (free, no key needed for basic forecast)
 * and transformed into agronomic advisories by WeatherInterpreter in the domain layer.
 *
 * Raw values (temperature, humidity) should never be displayed directly to users —
 * only the interpreted [advisory] field should be shown.
 */
@Entity(tableName = "weather_cache")
data class WeatherCacheEntity(
    @PrimaryKey
    val id: String,                          // UUID
    val date: String,                        // ISO date: "2026-02-24"
    val tempMinC: Double,
    val tempMaxC: Double,
    val rainfallMm: Double,
    val humidityPct: Int,
    val windSpeedKph: Double,
    val uvIndex: Double,
    /**
     * Agronomic advisory generated by WeatherInterpreter.
     * Values: OPTIMAL_CONDITIONS, HIGH_RAIN_RISK, DELAY_FERTILIZATION,
     *         OPTIMAL_PLANTING_WINDOW, DROUGHT_RISK, PEST_RISK_HIGH
     */
    val advisory: String,
    val advisoryDetail: String,              // Human-readable Tagalog/English detail
    val forecastType: String,               // "DAILY_FORECAST" | "HISTORICAL" | "SEASONAL"
    val fetchedAt: Long = System.currentTimeMillis()
)
